### ISSUE TITLE
Quilting bug

### ISSUE THREAD

**Issue by tdaede** [xiph/daala#11]

**Comment by negge** [comment]
I am able to reproduce this bug with the following steps:

./encoder_example -v 59 sintel_trailer_2k_short.y4m -o sintel.ogv
./player_example sintel.ogv

I screenshot of the quilting can be found here: http://people.xiph.org/~unlord/sintel-v59-quilting.png

**Comment by negge** [comment]
I am able to reproduce this bug with the following steps:

./encoder_example -v 59 sintel_trailer_2k_short.y4m -o sintel.ogv
./player_example sintel.ogv

I screenshot of the quilting can be found here: http://people.xiph.org/~unlord/sintel-v59-quilting.png

**Comment by tdaede** [comment]
Small test cases:
http://people.xiph.org/~tdaede/quilt.y4m
http://people.xiph.org/~tdaede/quilt_tiny.y4m

**Comment by tmatth** [comment]
Should be addressed by CLP filter (or future replacement) and/or full precision reference.
