### ISSUE TITLE
try constrained low pass loop filter

### ISSUE THREAD

**Issue by metajack** [xiph/daala#113]
See https://tools.ietf.org/html/draft-fuldseth-netvc-thor-00#section-8.2 for details.

**Comment by tmatth** [comment]
At what stage would this be applied?

**Comment by metajack** [comment]
The current code is run right before the bilinear filter and after the postfilter.

You can see my current code here:
https://github.com/metajack/daala/tree/clpf-skippy

**Comment by metajack** [comment]
Fixed by https://github.com/xiph/daala/commit/4b9c52880a29835d3083e4ed68fd7827274992ed
