### ISSUE TITLE
Update Quickstart Instructions

### ISSUE THREAD

**Issue by mbebenita** [xiph/daala#147]
On a brand new install of Ubuntu I ran `./autogen.sh` and it failed with the following message:
```
Makefile.am:7: error: Libtool library used but 'LIBTOOL' is undefined
```
I had to run `sudo apt-get install libtool libpng-dev` to get the build running.

**Comment by ycho** [comment]
You are lucky if only one was missing during building daala with ubunutu! :)

**Comment by tdaede** [comment]
it's a wiki, just edit it, which I did for you this time :)
