### ISSUE TITLE
Coded quantized = 63 does not work with encoder.

### ISSUE THREAD

**Issue by ycho** [xiph/daala#173]
Encoder works with coded quantizers 1 to 62 inclusive, but the largest quantizer 63 does not work and gives larger bitstream size.

For ex: /akiyo_cif_short.y4m with FPR off
-rw-rw-r-- 1 yushin yushin    903 Nov 30 14:04 master_q62_fpr_off.ogv
-rw-rw-r-- 1 yushin yushin   2879 Nov 30 14:05 master_q63_fpr_off.ogv

To reproduce above: need manually assign coded quantizer value in encode.c,
"enc->state.coded_quantizer[pli] = ".

**Comment by barrbrain** [comment]
There is an int32 overflow at https://github.com/xiph/daala/blob/1e0f85e1873db1dc289ea85883be808b1635098e/src/encode.c#L2107 for any quantizer value greater than 7405. Coded quantizer 62 has value 7338. Coded quantizer 63 has value 8191.

**Comment by tterribe** [comment]
So, the right thing to do is probably to reduce the precision of the Q23 constant so that things don't overflow.

**Comment by basarkoc** [comment]
Fixed in commit https://github.com/xiph/daala/commit/baac8f9575d7e27d4d72b66ee9d8a5862357fcad
