### ISSUE TITLE
Display bit per block in the stream analyzer

### ISSUE THREAD

**Issue by negge** [xiph/daala#27]
The bit accounting code needs to be modified to run in the decoder and exposed as a DECCTL.  This will require modifications so that the bit accounting code is not longer enabled / disabled in the decoder via the ./configure flag, but at runtime is enabled / disabled by the presence of a buffer supplied via DECCTL.

Display the bits per pixel per block as an heat map overlay to the image.

**Comment by RignonNoel** [comment]
@luctrudeau say this issues is done.

So we need to close it.
