### ISSUE TITLE
Add support for looping / replaying a video to stream analyzer

### ISSUE THREAD

**Issue by negge** [xiph/daala#28]
Right now the stream analyzer plays through the video once and then stops.  To play a second time, the video file must be reopened.  Add support for looping (via a check box menu item).  Internally, this will require implementing the DaalaDecoder::reset() so that the internal state of the decoder is reset rather than creating a new decoder.

**Comment by tmatth** [comment]
Fixed in commit 39003c1060f104276e2547c24e86f89612539549
