### ISSUE TITLE
Migrate stream analyzer to wxWidgets 3.0

### ISSUE THREAD

**Issue by negge** [xiph/daala#29]
The stream analyzer currently builds with wxWidgets 3.0, but there are UI errors that need to be fixed.  Once it works cleanly against 3.0, update the automake scripts so that it requires 3.0.0 to build in configure.ac.

**Comment by mbebenita** [comment]
We tried this recently and keyboard events were not working correctly with 3.0.2 on linux. OSX was working fine.

**Comment by RignonNoel** [comment]
Keyboard events has been fix :
https://github.com/xiph/daala/commit/8feaf5129659276255a1c70ae92ae5a304c50b80

Version 3.0.2 seems ok. We just need to update the ```configure.ac``` but @negge want wait we use feature of 3.0.2 before upgrade.

So i think this issue need to be close.

**Comment by jmvalin** [comment]
already works
