### ISSUE TITLE
Make all decoder ctl numbers odd

### ISSUE THREAD

**Issue by tterribe** [xiph/daala#32]
In Theora we had a convention that decoder ctl's (listed in include/daaladec.h) were all odd, as documented here <https://trac.xiph.org/browser/trunk/theora/include/theora/theoradec.h#L36>, so they would fail if accidentally passed to an encoder.

The current decoder controls in Daala do not follow this convention, but should.

The encoder also starts numbering at 4000 instead of 0, and does not use consecutive numbers, to make it less likely that arbitrary values passed to the function will trigger bad behavior, a convention we started during Opus development. The decoder should do something similar.

**Comment by suhasHere** [comment]
Review  : https://review.xiph.org/626/

**Comment by tterribe** [comment]
Fixed by #626.
