### ISSUE TITLE
Signal use of bilinear filter per-frame

### ISSUE THREAD

**Issue by tdaede** [xiph/daala#52]
The bilinear filter should be toggleable via an encoder option, ~~and have a per-frame enable/disable flag coded in the bitstream~~.

**Comment by negge** [comment]
There is no need to add a per frame flag in the bitstream.  The encoder can simply signal the bilinear filter is off on any blocks that are not skipped by setting the flag per block (which is already signaled).

**Comment by tmatth** [comment]
You could take this patch and just remove the signalling part: 
https://review.xiph.org/810/

**Comment by jmvalin** [comment]
there's no bilinear filter anymore
