### ISSUE TITLE
Some blocks are split but entirely skipped 

### ISSUE THREAD

**Issue by tdaede** [xiph/daala#65]
![screenshot from 2015-03-24 14 16 34](https://cloud.githubusercontent.com/assets/1308314/6813133/7537aa06-d230-11e4-85c1-5c2010086be9.png)

(red = anything was coded)

**Comment by jmvalin** [comment]
What's the status here. Is this really the case or was it just a visualization artefact?

**Comment by tdaede** [comment]
It's as you suspected, DC is not getting skipped. Which still raises the question of why it's better to code DC than a larger block.
