### ISSUE TITLE
Always output .y4m files with the same header

### ISSUE THREAD

**Issue by smarter** [xiph/daala#9]
The y4m header output by  `dump_video.c` starts with "YUV4MPEG2 C420jpeg H..." but the header output by `od_state_dump_yuv` in `state.c` starts with "YUV4MPEG2 W..." so we cannot check that they match by simply using `md5sum`. See http://wiki.multimedia.cx/index.php?title=YUV4MPEG2 for a pseudo-spec of y4m headers.

**Comment by suhasHere** [comment]
this is fixed from https://review.xiph.org/624
