### ISSUE TITLE
Remove dependency on libogg

### ISSUE THREAD

**Issue by tdaede** [xiph/daala#95]
libdaala(base|dec|enc) currently only use libogg for _ogg_malloc and ogg types. It would be nice to not rely on them.

**Comment by iankronquist** [comment]
Here is a list of the ogg types used, obtained using grep:
```
ogg_int16_t 
ogg_int32_t 
ogg_int64_t 
ogg_packet 
ogg_page 
ogg_stream_state 
ogg_sync_state 
ogg_uint16_t 
ogg_uint32_t
```

Here is a similar list of functions:
```
ogg_calloc(
ogg_free(
ogg_malloc(
ogg_page_bos(
ogg_page_eos(
ogg_page_granulepos(
ogg_page_packetout(
ogg_page_serialno(
ogg_realloc(
ogg_stream_clear(
ogg_stream_eos(
ogg_stream_flush(
ogg_stream_init(
ogg_stream_packetin(
ogg_stream_packetout(
ogg_stream_packetpeek(
ogg_stream_pagein(
ogg_stream_pageout(
ogg_sync_buffer(
ogg_sync_clear(
ogg_sync_init(
ogg_sync_pageout(
ogg_sync_wrote(
```

I think there is no standard type for the sync, page, and stream types, so you will still have to rely on ogg for those, unless you want to copy their implementations into daala. I could be ignorant here. I think the stdint.h types will work for the integer types and malloc & friends can be pulled from stdlib.h. Sound like a plan?

**Comment by tdaede** [comment]
The idea to remove ogg dependencies is only for libdaalaenc/dec/base. The examples parse the ogg container and will still require libogg.

**Comment by iankronquist** [comment]
Would you like me to remove malloc, free, and the integer types in the examples as well, or just leave all the ogg types alone?

**Comment by smarter** [comment]
Closing, this has been fixed by https://github.com/xiph/daala/commit/93b42d9e91f3bedcdf503f60466dfc3f3f49896b

**Comment by tdaede** [comment]
This is not fixed. Ogg types remain in the public APIs.

**Comment by tdaede** [comment]
This is now fixed for real.
