### ISSUE TITLE
Add a lossless encode to the ci on jenkins

### ISSUE THREAD

**Issue by negge** [xiph/daala#96]
Recently tmatth found that lossless was broken.  This is something that could be tested for with continuous integration on jenkins.

./configure --enable-encoder-check
examples/encoder_example -v 0 akiyo_qcif.y4m -o akiyo.ogv
File akiyo_qcif.y4m' is 176x144 29.970 fps 420 video.
Compressing...
pixel mismatch in row 0
pixel mismatch in row 1
pixel mismatch in row 2
pixel mismatch in row 3
pixel mismatch in row 4
pixel mismatch in row 5
pixel mismatch in row 6
pixel mismatch in row 7
pixel mismatch in row 8
pixel mismatch in row 9
pixel mismatch in row 10
....

**Comment by tmatth** [comment]
Fixed in commit 8cf864134ec105a5a3936f0f7625830e87192384
